import Head from 'next/head'
import styles from '../styles/Home.module.css'
import tokens from "@nimbus-ds/tokens/dist/js/tokens";

import Chart from "./components";
import { getAllCoverage, getAllOverrides } from "../lib/notion";

interface DataProps {
  coveragePeriods: [any];
  overridePeriods: [any];
}

export const getStaticProps = async () => {
  const rawCoverageData = await getAllCoverage()
  const rawOverridesData = await getAllOverrides()

  return {
    props: {
      coveragePeriods: rawCoverageData,
      overridePeriods: rawOverridesData
    },
    revalidate: 60
  };
};

const Home: React.FC<DataProps> = ({
  coveragePeriods,
  overridePeriods
}: DataProps) => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div style={{ width: "100%" }}>
          <h1>Coverage</h1>
          <Chart data={coveragePeriods} />
        </div>
        <div style={{ width: "100%" }}>
          <h1>Overrides</h1>
          <Chart data={overridePeriods} />
        </div>
      </main>
    </>
  )
}

export default Home;
